name: Dockerize Image Server

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:

  build-container:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCK_USERNAME }}
        password: ${{ secrets.DOCK_PASSWD }}
    - name: Build and Push Client
      uses: docker/build-push-action@v3
      with:
        context: .
        tags: techyfuzz123/simple-express-server:latest, techyfuzz123/simple-express-server:${{ github.run_number }}
        push: true
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new
