name: Dockerize Image Server

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:

  build-container:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCK_USERNAME }}
        password: ${{ secrets.DOCK_PASSWD }}
    - uses: docker/setup-buildx-action@v2
    - name: Build and Push
      uses: docker/build-push-action@v3
      with:
        context: .
	cache-from: type=gha
	cache-to: type=gha,mode=max
        tags: techyfuzz123/simple-express-server:latest, techyfuzz123/simple-express-server:${{ github.run_number }}
        push: true
